title: casualhacking

description: |
  A personal and public journal of technology exploration, usually about computer security and hardware.

baseurl: ""
url: "https://theopolis.github.io"

twitter_username: teddyreedv
github_username: theopolis

# Build settings
theme: minima
show_excerpts: true
permalink: /blog/:year/:i_month/:i_day/:title
excerpt_separator: <!--more-->
google_analytics: G-QLLJGFPY1P
plugins:
  - jekyll-feed
